name: Build

# Build project on pushes
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: |
          npm ci
          cd lib/functions/assets-cleanup && npm ci
          
      - name: Build project
        run: |
          npm run build
          cd lib/functions/assets-cleanup && npm run build